### ISSUE TITLE
Always returning false?

### ISSUE THREAD

**Issue by FilipQL** [nickurt/laravel-stopforumspam#1]
Hi, 

I am using _Laravel_ **6.9** and _nickurt/laravel-stopforumspam_ **1.5**. 
The following methods: 
```
\StopForumSpam::setEmail(...)->isSpamEmail();
\StopForumSpam::setIp(...)->isSpamIp()
```
always return `false`. 

For example, `adelaidaconnelly911@07stees.online` (taken from https://www.stopforumspam.com/domain/07stees.online) will be marked as "spam" if we use the API directly, by visiting http://api.stopforumspam.org/api?email=adelaidaconnelly911@07stees.online and downloading the XML response: 
```
<response success="true">
	<type>email</type>
	<appears>yes</appears>
	<lastseen>2020-03-09 20:39:27</lastseen>
	<frequency>1</frequency>
</response>
```
However, this: 
```
\StopForumSpam::setEmail('adelaidaconnelly911@07stees.online')->isSpamEmail()
```
... will return `false`.

**Comment by nickurt** [comment]
Hi FilipQL,

This seems to be the correct behaviour since the default threshold/frequency of the package is 10+

https://github.com/nickurt/laravel-stopforumspam/blob/1a7a7b85d354be6ad7935150029c8291ae592dc0/tests/StopForumSpamTest.php#L106-L127

When changing the threshold/frequency to 0 it will return true;

```php
\StopForumSpam::setEmail('adelaidaconnelly911@07stees.online')->setFrequency(0)->isSpamEmail()
```

**Comment by FilipQL** [comment]
@nickurt Thanks!

**Comment by FilipQL** [comment]
@nickurt One suggestion: maybe in "_Manual Usage_" examples (in `README.md`) we could have `->setFrequency(int)` method mentioned :) 
Thanks for the package!
